export const FETCH_QUISES_START = 'FETCH_QUISES_START'
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS'
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR'
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS'

export const REPEAT_QUIZ = 'REPEAT_QUIZ'
export const QUIZ_SET_STATE = 'QUIZ_SET_STATE'
export const QUIS_FINISH = 'QUIS_FINISH'
export const NEXT_QUESTION = 'NEXT_QUESTION'

export const CREATE_QUESTION = 'CREATE_QUESTION'
export const RESET_QUIZ = 'RESET_QUIZ'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
